import type { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
    /**
     * Cleanup
     */
    await knex("brands").del();
    await knex("types").del();
    await knex("resellers").del();
    await knex("statuses").del();
    await knex("assets").del();

    /**
     * Insert data
     */
    await knex("brands").insert([
        { id: 1, name: "Lenovo" },
        { id: 2, name: "HP" },
        { id: 3, name: "Dell" },
        { id: 4, name: "Apple" },
        { id: 5, name: "Asus" },
        { id: 6, name: "Acer" },
    ]);

    await knex("types").insert([
        { id: 1, name: "Smartphone" },
        { id: 2, name: "Tablet" },
        { id: 3, name: "Laptop" },
        { id: 4, name: "PC" },
        { id: 5, name: "Monitor" },
    ]);

    await knex("resellers").insert([
        { id: 1, name: "Amazon" },
        { id: 2, name: "Temu" },
    ]);

    await knex("statuses").insert([
        { id: 1, name: "Available" },
        { id: 2, name: "In Use" },
        { id: 3, name: "Under Repair" },
        { id: 4, name: "Stolen" },
        { id: 5, name: "Retired" },
    ]);

    await knex("assets").insert([
        {
            id: 1,
            brand_id: 1,
            type_id: 3,
            reseller_id: 1,
            status_id: 2,
            purchased_at: "2025-03-01",
            model: "Thinkpad 7420",
            serial: "SN-DL-001-7420",
            warranty_months: 36,
            price: "1299.99",
        },
        {
            id: 2,
            brand_id: 2,
            type_id: 3,
            reseller_id: 1,
            status_id: 1,
            purchased_at: "2024-11-15",
            model: "EliteBook 850",
            serial: "SN-HP-002-850",
            warranty_months: 24,
            price: "1149.00",
        },
        {
            id: 3,
            brand_id: 3,
            type_id: 4,
            reseller_id: 2,
            status_id: 2,
            purchased_at: "2024-07-21",
            model: "OptiPlex 7010",
            serial: "SN-DE-003-7010",
            warranty_months: 36,
            price: "899.50",
        },
        {
            id: 4,
            brand_id: 4,
            type_id: 3,
            reseller_id: 1,
            status_id: 1,
            purchased_at: "2025-01-10",
            model: "MacBook Pro 14",
            serial: "SN-AP-004-MBP14",
            warranty_months: 24,
            price: "2399.99",
        },
        {
            id: 5,
            brand_id: 5,
            type_id: 5,
            reseller_id: 2,
            status_id: 3,
            purchased_at: "2023-09-08",
            model: "ProArt Display",
            serial: "SN-AS-005-PRO",
            warranty_months: 24,
            price: "499.90",
        },
        {
            id: 6,
            brand_id: 6,
            type_id: 4,
            reseller_id: 1,
            status_id: 1,
            purchased_at: "2024-05-14",
            model: "Aspire TC",
            serial: "SN-AC-006-TC",
            warranty_months: 24,
            price: "699.99",
        },
        {
            id: 7,
            brand_id: 1,
            type_id: 5,
            reseller_id: 1,
            status_id: 2,
            purchased_at: "2023-12-11",
            model: "ThinkVision T24",
            serial: "SN-LE-007-T24",
            warranty_months: 36,
            price: "219.99",
        },
        {
            id: 8,
            brand_id: 2,
            type_id: 1,
            reseller_id: 2,
            status_id: 1,
            purchased_at: "2025-02-22",
            model: "HP Elite Dragonfly",
            serial: "SN-HP-008-DRG",
            warranty_months: 24,
            price: "999.99",
        },
        {
            id: 9,
            brand_id: 3,
            type_id: 3,
            reseller_id: 1,
            status_id: 5,
            purchased_at: "2022-04-03",
            model: "Latitude 5530",
            serial: "SN-DE-009-5530",
            warranty_months: 36,
            price: "1349.00",
        },
        {
            id: 10,
            brand_id: 4,
            type_id: 2,
            reseller_id: 1,
            status_id: 2,
            purchased_at: "2024-10-01",
            model: "iPad Air",
            serial: "SN-AP-010-AIR",
            warranty_months: 12,
            price: "749.99",
        },
        {
            id: 11,
            brand_id: 5,
            type_id: 3,
            reseller_id: 2,
            status_id: 4,
            purchased_at: "2023-06-18",
            model: "ZenBook 14",
            serial: "SN-AS-011-Z14",
            warranty_months: 24,
            price: "1099.99",
        },
        {
            id: 12,
            brand_id: 6,
            type_id: 3,
            reseller_id: 1,
            status_id: 1,
            purchased_at: "2025-04-01",
            model: "Swift X",
            serial: "SN-AC-012-SWX",
            warranty_months: 24,
            price: "1249.00",
        },
        {
            id: 13,
            brand_id: 1,
            type_id: 4,
            reseller_id: 2,
            status_id: 2,
            purchased_at: "2024-08-08",
            model: "ThinkCentre M90",
            serial: "SN-LE-013-M90",
            warranty_months: 36,
            price: "849.99",
        },
        {
            id: 14,
            brand_id: 2,
            type_id: 5,
            reseller_id: 1,
            status_id: 1,
            purchased_at: "2025-01-30",
            model: "HP E27 G5",
            serial: "SN-HP-014-E27",
            warranty_months: 24,
            price: "289.99",
        },
        {
            id: 15,
            brand_id: 3,
            type_id: 1,
            reseller_id: 2,
            status_id: 3,
            purchased_at: "2024-03-12",
            model: "Dell Mobile Pro",
            serial: "SN-DE-015-MOB",
            warranty_months: 12,
            price: "599.99",
        },
        {
            id: 16,
            brand_id: 4,
            type_id: 5,
            reseller_id: 1,
            status_id: 1,
            purchased_at: "2023-11-25",
            model: "Studio Display",
            serial: "SN-AP-016-STU",
            warranty_months: 24,
            price: "1749.00",
        },
        {
            id: 17,
            brand_id: 5,
            type_id: 2,
            reseller_id: 2,
            status_id: 2,
            purchased_at: "2024-09-19",
            model: "Transformer Tab",
            serial: "SN-AS-017-TTAB",
            warranty_months: 18,
            price: "649.90",
        },
        {
            id: 18,
            brand_id: 6,
            type_id: 5,
            reseller_id: 1,
            status_id: 5,
            purchased_at: "2022-02-14",
            model: "Nitro Display 27",
            serial: "SN-AC-018-N27",
            warranty_months: 12,
            price: "329.99",
        },
        {
            id: 19,
            brand_id: 1,
            type_id: 1,
            reseller_id: 2,
            status_id: 1,
            purchased_at: "2025-03-28",
            model: "Moto Enterprise",
            serial: "SN-LE-019-MOTO",
            warranty_months: 24,
            price: "799.00",
        },
        {
            id: 20,
            brand_id: 3,
            type_id: 5,
            reseller_id: 1,
            status_id: 2,
            purchased_at: "2024-12-05",
            model: "UltraSharp U2723",
            serial: "SN-DE-020-U27",
            warranty_months: 36,
            price: "579.99",
        },
    ]);
};
